name: matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        # below this can be used to add single combinations
        include:
          - node-version: 18
            operating-system: ubuntu-latest 
        exclude:
          - node-version: 12
            operating-system: windows-latest
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: NodeJs Install
        uses: actions/setup-node@v3
        with:
          #   node-version: 14
          node-version: ${{ matrix.node-version}}

      - name: Install the dependencies
        run: npm ci

      - name: Build the project
        run: npm run build
