name: Reusable workflows
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the deployable artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: result of the deployable operation
        value: ${{ jobs.deploy.outputs.outcome}}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output the DC information
        run: echo "Dinesh"
      - name: set output result
        id: set-result
        run: echo "::set-output name=step-result::success"
